cloudflared_token: "{{ lookup('env', 'CLOUDFLARED_TUNNEL_TOKEN') }}"
vpn_wg_private_key: "{{ lookup('env', 'WIREGUARD_PRIVATE_KEY') }}"
vpn_country: "{{ lookup('env', 'VPN_COUNTRY') | default('', true) }}"
plex_claim: "{{ lookup('env', 'PLEX_CLAIM') }}"
plex_token: "{{ lookup('env', 'PLEX_TOKEN') }}"
tautulli_api_key: "{{ lookup('env', 'TAUTULLI_API_KEY') }}"
prowlarr_api_key: "{{ lookup('env', 'PROWLARR_API_KEY') }}"
sonarr_api_key: "{{ lookup('env', 'SONARR_API_KEY') }}"
radarr_api_key: "{{ lookup('env', 'RADARR_API_KEY') }}"
apps_user: apps
config_dir: "/home/apps/config"
install_dir: "/home/apps"
