cloudflared_token: "{{ lookup('env', 'CLOUDFLARED_TUNNEL_TOKEN') }}"
vpn_wg_private_key: "{{ lookup('env', 'WIREGUARD_PRIVATE_KEY') }}"
vpn_country: "{{ lookup('env', 'VPN_COUNTRY') | default('', true) }}"
plex_claim: "{{ lookup('env', 'PLEX_CLAIM') }}"
plex_token: "{{ lookup('env', 'PLEX_TOKEN') }}"
tautulli_api_key: "{{ lookup('env', 'TAUTULLI_API_KEY') }}"
prowlarr_api_key: "{{ lookup('env', 'PROWLARR_API_KEY') }}"
sonarr_api_key: "{{ lookup('env', 'SONARR_API_KEY') }}"
radarr_api_key: "{{ lookup('env', 'RADARR_API_KEY') }}"
bazarr_api_key: "{{ lookup('env', 'BAZARR_API_KEY') }}"
homeassistant_token: "{{ lookup('env', 'HOMEASSISTANT_TOKEN') }}"
romm_db_password: "{{ lookup('env', 'ROMM_DB_PASSWORD') }}"
romm_auth_secret: "{{ lookup('env', 'ROMM_AUTH_SECRET') }}"
romm_igdb_client_id: "{{ lookup('env', 'ROMM_IGDB_CLIENT_ID') }}"
romm_igdb_client_secret: "{{ lookup('env', 'ROMM_IGDB_CLIENT_SECRET') }}"
romm_retroachievements_api_key: "{{ lookup('env', 'ROMM_RETROACHIEVEMENTS_API_KEY') }}"
romm_steamgriddb_api_key: "{{ lookup('env', 'ROMM_STEAMGRIDDB_API_KEY') }}"
apps_user: apps
config_dir: "/home/apps/config"
install_dir: "/home/apps"
